<?php
// Path: MES/page/PE/api/generate_wo_pdf.php

require_once __DIR__ . '/../../../utils/libs/tcpdf/tcpdf.php'; 
require_once __DIR__ . '/../../db.php';
require_once __DIR__ . '/../../components/init.php';

requirePermission(['view_maintenance', 'view_production', 'view_dashboard']);

$wo_id = $_GET['wo_id'] ?? null;
if (!$wo_id) {
    die("Work Order ID is required.");
}

// 1. Fetch Work Order Data
$sql = "SELECT W.*, M.machine_name, U1.fullname AS req_fullname, U2.fullname AS tech_fullname
        FROM " . PE_WORK_ORDERS_TABLE . " W WITH (NOLOCK)
        LEFT JOIN " . PE_MACHINES_TABLE . " M WITH (NOLOCK) ON W.machine_id = M.machine_id
        LEFT JOIN USERS U1 WITH (NOLOCK) ON W.requested_by = U1.username
        LEFT JOIN USERS U2 WITH (NOLOCK) ON W.assigned_to = U2.username
        WHERE W.wo_id = ?";
$stmt = $pdo->prepare($sql);
$stmt->execute([$wo_id]);
$wo = $stmt->fetch(PDO::FETCH_ASSOC);

$requested_by_display = $wo['req_fullname'] ? $wo['req_fullname'] : $wo['requested_by'];
$assigned_to_display = $wo['tech_fullname'] ? $wo['tech_fullname'] : $wo['assigned_to'];

if (!$wo) {
    die("Work Order not found.");
}

// 2. Class for Footer (Compact Mode)
if (!class_exists('PE_WO_PDF')) {
    class PE_WO_PDF extends TCPDF {
        public function Footer() {
            $this->SetY(-10); // ขยับ Footer ขึ้นมาหน่อย
            $this->SetFont('freeserif', 'I', 7); // ลดขนาดฟอนต์
            $this->SetTextColor(128, 128, 128);
            $this->Cell(0, 10, 'Generated by MES System | Ref: FM-MTD-013/R00:15/11/17', 0, false, 'R', 0, '', 0, false, 'T', 'M');
        }
    }
}

// Helper Functions
if (!function_exists('formatDateTH_PDF')) {
    function formatDateTH_PDF($date) { return $date ? date('d/m/Y', strtotime($date)) : "-"; }
}
if (!function_exists('formatTime_PDF')) {
    function formatTime_PDF($date) { return $date ? date('H:i', strtotime($date)) : "-"; }
}

// 3. Process Image Path
$rootDir = realpath(__DIR__ . '/../../../'); // Root MES dir
$photoPath = '';
if (!empty($wo['image_path'])) {
    $cleanPath = str_replace('../../uploads/', 'uploads/', $wo['image_path']);
    $fullPath = $rootDir . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, ltrim($cleanPath, '/'));
    if (file_exists($fullPath)) {
        $photoPath = $fullPath;
    }
}

$photoAfterPath = '';
if (!empty($wo['photo_after'])) {
    $cleanPathAfter = str_replace('../../uploads/', 'uploads/', $wo['photo_after']);
    $fullPathAfter = $rootDir . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, ltrim($cleanPathAfter, '/'));
    if (file_exists($fullPathAfter)) {
        $photoAfterPath = $fullPathAfter;
    }
}

// 4. Setup TCPDF (Compact Mode)
$pdf = new PE_WO_PDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->SetCreator('PE Enterprise');
$pdf->SetTitle('Work Order ' . $wo['wo_number']);

$pdf->SetMargins(10, 8, 10); 
$pdf->SetAutoPageBreak(TRUE, 8);
$pdf->SetFont('freeserif', '', 10); // Base font 10

$pdf->setCellPaddings(0, 0, 0, 0); 
$pdf->setCellHeightRatio(1.0); 

$pdf->AddPage();

// 5. HTML Construction (Modern Compact)
$html = '
<style>
    .header-title { font-size: 16px; font-weight: bold; color: #000000; }
    .header-sub { font-size: 10px; color: #333333; }
    .job-id { font-size: 12px; font-weight: bold; color: #000000; text-align: right; }
    
    .section-title { font-size: 11px; font-weight: bold; color: #111111; border-bottom: 1px solid #999999; line-height: 16px;}
    
    .label { color: #444444; font-size: 9px; font-weight: bold; text-transform: uppercase; }
    .value { color: #000000; font-size: 10px; }
    
    .box { background-color: #ffffff; border: 1px solid #cccccc; padding: 5px; }
</style>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td width="70%">
            <span class="header-title">MAINTENANCE WORK ORDER</span><br>
            <span class="header-sub">ใบแจ้งซ่อมเครื่องจักร (PE Enterprise)</span>
        </td>
        <td width="30%" align="right" style="vertical-align: bottom;">
            <span class="label">WO NO.</span><br>
            <span class="job-id">' . htmlspecialchars($wo['wo_number']) . '</span>
        </td>
    </tr>
</table>

<div style="height: 10px;"></div>';

// --- SECTION 1: REQUEST INFO ---
$html .= '
<div class="section-title">1. REQUEST INFORMATION (ข้อมูลการแจ้งซ่อม)</div>
<div style="height: 5px;"></div>

<table border="0" cellpadding="3" cellspacing="0" width="100%" style="background-color: #f4f6f7;">
    <tr>
        <td width="30%">
            <span class="label">MACHINE</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value" style="font-weight:bold;">' . htmlspecialchars($wo['machine_name'] ?? '-') . '</span>
        </td>
        <td width="20%">
            <span class="label">LINE</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . htmlspecialchars($wo['line'] ?? '-') . '</span>
        </td>
        <td width="30%">
            <span class="label">REQUESTER</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . htmlspecialchars($requested_by_display ?? '-') . '</span>
        </td>
        <td width="20%">
            <span class="label">DATE</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . formatDateTH_PDF($wo['requested_at']) . ' ' . formatTime_PDF($wo['requested_at']) . '</span>
        </td>
    </tr>
</table>

<div style="height: 5px;"></div>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td width="100%">
            <span class="label">ISSUE SUMMARY (หัวข้อปัญหา)</span><br>
            <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                <span class="value" style="font-weight:bold;">' . nl2br(htmlspecialchars($wo['issue_title'] ?? '-')) . '</span>
            </div>
        </td>
    </tr>
    <tr>
        <td width="100%">
            <div style="height: 5px;"></div>
            <span class="label">ISSUE DESCRIPTION (รายละเอียดปัญหา)</span><br>
            <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                <span class="value">' . nl2br(htmlspecialchars($wo['issue_detail'] ?? '-')) . '</span>
            </div>
        </td>
    </tr>
</table>

<div style="height: 10px;"></div>';

// --- SECTION 2: RESOLUTION INFO ---
$html .= '
<div class="section-title">2. RESOLUTION DETAILS (รายละเอียดการซ่อม)</div>
<div style="height: 5px;"></div>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td width="100%">
            <span class="label">ROOT CAUSE (สาเหตุรากฐาน)</span><br>
            <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                <span class="value">' . nl2br(htmlspecialchars($wo['root_cause'] ?? '-')) . '</span>
            </div>
        </td>
    </tr>
    <tr>
        <td width="100%">
            <div style="height: 5px;"></div>
            <span class="label">ACTION TAKEN (การแก้ไข)</span><br>
            <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                <span class="value">' . nl2br(htmlspecialchars($wo['action_taken'] ?? '-')) . '</span>
            </div>
        </td>
    </tr>
</table>

<div style="height: 5px;"></div>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td width="100%">
            <span class="label">SPARE PARTS (อะไหล่ที่ใช้)</span><br>
            <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">';
            
$parts = preg_split('/[\r\n]+/', $wo['parts_used'] ?? '');
$hasParts = false;
$partsHtml = '';
foreach ($parts as $part) {
    $part = trim($part);
    if (!empty($part)) {
        $hasParts = true;
        $partsHtml .= '<span class="value">- ' . htmlspecialchars(ltrim($part, '.-• ')) . '</span><br>';
    }
}
$html .= $hasParts ? $partsHtml : '<span class="value">-</span>';

$html .= '  </div>
        </td>
    </tr>
</table>

<div style="height: 5px;"></div>

<table border="0" cellpadding="3" cellspacing="0" width="100%" style="background-color: #f4f6f7;">
    <tr>
        <td width="25%">
            <span class="label">START TIME</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . formatDateTH_PDF($wo['started_at']) . ' ' . formatTime_PDF($wo['started_at']) . '</span>
        </td>
        <td width="25%">
            <span class="label">FINISH TIME</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . formatDateTH_PDF($wo['completed_at']) . ' ' . formatTime_PDF($wo['completed_at']) . '</span>
        </td>
        <td width="25%">
            <span class="label">REPAIR TIME</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value">' . htmlspecialchars($wo['repair_minutes'] ?? '0') . ' min</span>
        </td>
        <td width="25%">
            <span class="label">TECHNICIAN</span>
            <div style="font-size: 1px; line-height: 1px;">&nbsp;</div>
            <span class="value" style="font-weight:bold;">' . htmlspecialchars($assigned_to_display ?? '-') . '</span>
        </td>
    </tr>
</table>

<div style="height: 10px;"></div>';

// --- SECTION 3: IMAGES ---
$html .= '
<div class="section-title">3. JOB PHOTOS (รูปภาพประกอบ)</div>
<div style="height: 3px;"></div>

<table border="0" cellpadding="2" cellspacing="0" width="100%">
    <tr>
        <td width="50%" align="center">
            <div style="border: 1px solid #ccc; padding: 2px; height: 140px;">
                <div style="font-size: 8px; color: #7f8c8d; margin-bottom: 2px;">BEFORE</div>';
if ($photoPath) {
    $html .= '<img src="' . $photoPath . '" height="120" border="0">';
} else {
    $html .= '<br><br><br><span style="color:#ccc; font-size:10px;">- No Image -</span>';
}
$html .= '  </div>
        </td>
        <td width="50%" align="center">
            <div style="border: 1px solid #ccc; padding: 2px; height: 140px;">
                <div style="font-size: 8px; color: #7f8c8d; margin-bottom: 2px;">AFTER</div>';
if ($photoAfterPath) {
    $html .= '<img src="' . $photoAfterPath . '" height="120" border="0">';
} else {
    $html .= '<br><br><br><span style="color:#ccc; font-size:10px;">- No Image -</span>';
}
$html .= '  </div>
        </td>
    </tr>
</table>

<div style="height: 10px;"></div>';

// --- SECTION 4: SIGNATURES ---
$html .= '
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td width="5%"></td>
        <td width="40%" align="center" style="border-top: 1px solid #999;">
            <div style="font-size: 2px; line-height: 2px;">&nbsp;</div>
            <span class="value">' . htmlspecialchars($requested_by_display ?? '-') . '</span>
            <div style="font-size: 2px; line-height: 2px;">&nbsp;</div>
            <span class="label">REQUESTER SIGNATURE</span>
        </td>
        <td width="10%"></td>
        <td width="40%" align="center" style="border-top: 1px solid #999;">
            <div style="font-size: 2px; line-height: 2px;">&nbsp;</div>
            <span class="value">' . htmlspecialchars($assigned_to_display ?? '-') . '</span>
            <div style="font-size: 2px; line-height: 2px;">&nbsp;</div>
            <span class="label">TECHNICIAN SIGNATURE</span>
        </td>
        <td width="5%"></td>
    </tr>
</table>';

$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('WO_' . $wo['wo_number'] . '.pdf', 'I'); 
?>
