<?php
// Agent API Example Script
// This script simulates an AI Agent checking a user's timeline and adding a new task.

$apiUrl = 'https://oem.sncformer.com/iot-toolbox/sandbox-b9/Toolbox/plannerAgent/api/agent_api.php';
$targetUser = 'naphat-noo'; // Will resolve to the user's AKA or actual name via the API's LIKE %user% logic
$targetUser = 'Oat'; // Using the user's AKA (Oat) for planner tasks

echo "1. Getting Timeline for user: $targetUser\n";
$getTimelineUrl = $apiUrl . "?action=get_timeline&user=" . urlencode($targetUser);

$ch = curl_init($getTimelineUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// Need to accept self-signed certs if testing internally
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

echo "HTTP Code: $httpCode\n";
if ($httpCode === 200) {
    $timeline = json_decode($response, true);
    if ($timeline['success']) {
        echo "Found " . count($timeline['data']) . " ongoing tasks.\n";
    } else {
        echo "API Error: " . $timeline['message'] . "\n";
    }
} else {
    echo "Failed to get timeline. Response: $response\n";
}

echo "\n2. Creating a new Task for $targetUser\n";

$newTask = [
    'title' => 'Agent System Health Check',
    'description' => "This is an automated task generated by the AI Agent to verify the API integration works properly.\nGenerated at: " . date('Y-m-d H:i:s'),
    'assignee' => $targetUser,
    'startDate' => date('Y-m-d'),
    'dueDate' => date('Y-m-d', strtotime('+1 day')),
    'status' => 'active',
    'priority' => 'high',
    'tags' => 'AI,Agent,System',
    'spaceId' => 1, // Change if needed, usually 1 is General or something
    'checklist' => json_encode([
        ['id' => uniqid(), 'text' => 'Verify task appeared on timeline', 'isDone' => false],
        ['id' => uniqid(), 'text' => 'Verify checklist items render correctly', 'isDone' => false],
        ['id' => uniqid(), 'text' => 'Verify tags and priority', 'isDone' => false]
    ])
];

$ch = curl_init($apiUrl . "?action=create_task&user=" . urlencode($targetUser));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($newTask));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$createResponse = curl_exec($ch);
$createHttpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

echo "Create Task HTTP Code: $createHttpCode\n";
echo "Response: $createResponse\n";

?>
