<?php
ini_set('display_errors', 0);
error_reporting(E_ALL);

// เรียกใช้ db.php ซึ่งได้โหลด config.php ไว้แล้ว
require_once __DIR__ . '/../../db.php';
require_once __DIR__ . '/../../../auth/check_auth.php';

header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    if (empty($_SERVER['HTTP_X_CSRF_TOKEN']) || empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $_SERVER['HTTP_X_CSRF_TOKEN'])) {
        http_response_code(403);
        echo json_encode(['success' => false, 'message' => 'CSRF Token Validation Failed.']);
        exit;
    }
}

$action = $_REQUEST['action'] ?? '';
$input = json_decode(file_get_contents("php://input"), true) ?: $_POST;

if (!hasRole(['admin', 'creator'])) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Unauthorized Access.']);
    exit;
}

try {
    $currentUser = $_SESSION['user'];
    $actionBy = $currentUser['username'];

    switch ($action) {
        case 'read':
            $stmt = $pdo->query("SELECT id, username, fullname, role, line, team_group, emp_id, is_active, is_auto_generated, created_at 
                                 FROM " . USERS_TABLE . " 
                                 WHERE role != 'creator' 
                                 ORDER BY is_active DESC, role ASC, id ASC");
            $users = $stmt->fetchAll(PDO::FETCH_ASSOC);
            echo json_encode(['success' => true, 'data' => $users]);
            break;

        case 'sync_manpower':
            // 1. อัปเดตข้อมูลพนักงานที่มี User อยู่แล้ว
            $stmtSync = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_SyncExistingUsersFromManpower @ActionBy=?");
            $stmtSync->execute([$actionBy]);
            $syncResult = $stmtSync->fetch(PDO::FETCH_ASSOC);
            $updatedCount = $syncResult['updated_count'] ?? 0;

            // 2. กวาดพนักงานที่ยังไม่มี User มาสร้างใหม่ (ดึง department_api มาด้วย)
            $stmtNew = $pdo->query("
                SELECT emp_id, name_th, line, department_api 
                FROM " . MANPOWER_EMPLOYEES_TABLE . " 
                WHERE is_active = 1 
                  AND emp_id NOT IN (SELECT emp_id FROM " . USERS_TABLE . " WHERE emp_id IS NOT NULL)
                  AND emp_id NOT IN (SELECT username FROM " . USERS_TABLE . " WHERE username IS NOT NULL)
            ");
            $newEmployees = $stmtNew->fetchAll(PDO::FETCH_ASSOC);

            $addedCount = 0;
            $stmtAddUser = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_ManageUser @Action='ADD', @Username=?, @PasswordHash=?, @Role='operator', @Line=?, @EmpId=?, @Fullname=?, @TeamGroup=?, @IsAutoGenerated=1, @ActionBy=?");

            foreach ($newEmployees as $emp) {
                $empId = trim($emp['emp_id']);
                if(strlen($empId) < 4) continue; 

                $username = $empId;
                $password = substr($empId, -4); 
                $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
                
                // Dynamic Extraction สำหรับสร้างคนใหม่ (PHP)
                $teamGroup = null;
                $dept = $emp['department_api'] ?? '';
                if (strpos($dept, '-') !== false) {
                    $parts = explode('-', $dept);
                    $afterDash = trim($parts[1] ?? '');
                    $subParts = explode(' ', $afterDash);
                    if (!empty($subParts[0]) && strtoupper($subParts[0]) !== 'UNASSIGNED') {
                        $teamGroup = strtoupper($subParts[0]);
                    }
                }
                
                $stmtAddUser->execute([
                    $username, $hashedPassword, $emp['line'], $empId, $emp['name_th'], $teamGroup, $actionBy
                ]);
                $addedCount++;
            }

            echo json_encode([
                'success' => true, 
                'message' => "Sync Complete. Updated: {$updatedCount}, Added: {$addedCount} new users."
            ]);
            break;

        case 'get_emp_info':
            $empId = trim($_GET['emp_id'] ?? '');
            if (!$empId) throw new Exception("Employee ID is required");
            
            $stmt = $pdo->prepare("
                SELECT name_th, line, department_api 
                FROM " . MANPOWER_EMPLOYEES_TABLE . " 
                WHERE emp_id = ?
            ");
            $stmt->execute([$empId]);
            $emp = $stmt->fetch(PDO::FETCH_ASSOC);
            
            if ($emp) {
                // Dynamic Extraction (PHP)
                $teamGroup = '';
                $dept = $emp['department_api'] ?? '';
                if (strpos($dept, '-') !== false) {
                    $parts = explode('-', $dept);
                    $afterDash = trim($parts[1] ?? ''); // เช่น "Team1 D-DL" หรือ "B9 D-DL"
                    $subParts = explode(' ', $afterDash);
                    if (!empty($subParts[0]) && strtoupper($subParts[0]) !== 'UNASSIGNED') {
                        $teamGroup = strtoupper($subParts[0]); // ได้ "TEAM1" หรือ "B9"
                    }
                }

                echo json_encode(['success' => true, 'data' => [
                    'name_th' => $emp['name_th'],
                    'line' => $emp['line'],
                    'team_group' => $teamGroup
                ]]);
            } else {
                echo json_encode(['success' => false, 'message' => 'Not found']);
            }
            break;

        case 'create':
        case 'update':
            $targetId = (int)($input['id'] ?? 0);
            $username = trim($input['username'] ?? '');
            $role = trim($input['role'] ?? '');
            $line = !empty(trim($input['line'] ?? '')) ? strtoupper(trim($input['line'])) : null;
            $emp_id = !empty(trim($input['emp_id'] ?? '')) ? trim($input['emp_id']) : null;
            $fullname = !empty(trim($input['fullname'] ?? '')) ? trim($input['fullname']) : null;
            $team_group = !empty(trim($input['team_group'] ?? '')) ? strtoupper(trim($input['team_group'])) : null;
            $password = trim($input['password'] ?? '');

            if (empty($role)) throw new Exception("Role is required.");
            if ($role === 'creator') throw new Exception("Cannot manage 'creator' role via UI.");
            if ($role === 'admin' && !hasRole('creator')) throw new Exception("Only creators can manage admin users.");

            if ($action === 'create') {
                if (empty($username) || empty($password)) throw new Exception("Username and password are required.");
                $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
                $stmt = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_ManageUser @Action='ADD', @Username=?, @PasswordHash=?, @Role=?, @Line=?, @EmpId=?, @Fullname=?, @TeamGroup=?, @ActionBy=?");
                $stmt->execute([$username, $hashedPassword, $role, $line, $emp_id, $fullname, $team_group, $actionBy]);
                echo json_encode(['success' => true, 'message' => 'User created successfully.']);
            } else {
                if (!$targetId) throw new Exception("Target user ID is required.");
                
                $stmtUpdate = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_ManageUser @Action='EDIT', @UserId=?, @Role=?, @Line=?, @EmpId=?, @Fullname=?, @TeamGroup=?, @ActionBy=?");
                $stmtUpdate->execute([$targetId, $role, $line, $emp_id, $fullname, $team_group, $actionBy]);

                if (!empty($password)) {
                    $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
                    $stmtPwd = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_ManageUser @Action='RESET_PWD', @UserId=?, @PasswordHash=?, @ActionBy=?");
                    $stmtPwd->execute([$targetId, $hashedPassword, $actionBy]);
                }
                echo json_encode(['success' => true, 'message' => 'User updated successfully.']);
            }
            break;

        case 'toggle_status':
            $targetId = (int)($input['id'] ?? $_GET['id'] ?? 0);
            if (!$targetId) throw new Exception("Missing user ID.");
            if ($targetId === (int)$currentUser['id']) throw new Exception("You cannot disable your own account.");
            
            $stmtToggle = $pdo->prepare("EXEC " . DB_DATABASE . ".dbo.sp_ManageUser @Action='TOGGLE_STATUS', @UserId=?, @ActionBy=?");
            $stmtToggle->execute([$targetId, $actionBy]);
            echo json_encode(['success' => true, 'message' => 'User status updated.']);
            break;
            
        case 'logs':
            $page = max(1, intval($_GET['page'] ?? 1));
            $limit = max(1, intval($_GET['limit'] ?? 50));
            $startRow = ($page - 1) * $limit;
            
            $conditions = []; $params = [];
            if (!empty($_GET['startDate'])) { $conditions[] = "CAST(created_at AS DATE) >= ?"; $params[] = $_GET['startDate']; }
            if (!empty($_GET['endDate'])) { $conditions[] = "CAST(created_at AS DATE) <= ?"; $params[] = $_GET['endDate']; }
            if (!empty($_GET['user'])) { $conditions[] = "action_by LIKE ?"; $params[] = '%' . $_GET['user'] . '%'; }
            if (!empty($_GET['action_type'])) { $conditions[] = "action_type LIKE ?"; $params[] = '%' . $_GET['action_type'] . '%'; }
            if (!empty($_GET['target'])) { $conditions[] = "target_user LIKE ?"; $params[] = '%' . $_GET['target'] . '%'; }
            
            $whereClause = $conditions ? "WHERE " . implode(" AND ", $conditions) : "";

            $totalStmt = $pdo->prepare("SELECT COUNT(*) AS total FROM " . USER_LOGS_TABLE . " $whereClause");
            $totalStmt->execute($params);
            $total = (int)$totalStmt->fetch()['total'];
            
            $dataSql = "SELECT * FROM ( SELECT id, action_by, action_type, target_user, detail, created_at, ROW_NUMBER() OVER (ORDER BY created_at DESC, id DESC) AS RowNum FROM " . USER_LOGS_TABLE . " $whereClause ) AS NumberedRows WHERE RowNum > ? AND RowNum <= ?";
            
            $paginationParams = array_merge($params, [$startRow, $startRow + $limit]);
            $dataStmt = $pdo->prepare($dataSql);
            $dataStmt->execute($paginationParams);
            $logs = $dataStmt->fetchAll(PDO::FETCH_ASSOC);

            foreach ($logs as &$log) {
                if ($log['created_at']) {
                    $log['created_at'] = (new DateTime($log['created_at']))->format('Y-m-d H:i:s');
                }
            }
            
            echo json_encode(['success' => true, 'data' => $logs, 'total' => $total, 'page' => $page, 'limit' => $limit]);
            break;

        default:
            throw new Exception("Invalid action specified.");
    }
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
}
?>