<?php
// Path: MES/page/Stop_Cause/api/generate_job_pdf.php

require_once __DIR__ . '/../../../utils/libs/tcpdf/tcpdf.php'; 

// --- 1. Class Footer (Compact) ---
if (!class_exists('MYPDF')) {
    class MYPDF extends TCPDF {
        public function Footer() {
            $this->SetY(-10); // ขยับ Footer ขึ้นมาหน่อย
            $this->SetFont('freeserif', 'I', 7); // ลดขนาดฟอนต์
            $this->SetTextColor(128, 128, 128);
            $this->Cell(0, 10, 'Generated by MES System | Ref: FM-MTD-013', 0, false, 'R', 0, '', 0, false, 'T', 'M');
        }
    }
}

function generateJobOrderPDF($pdo, $jobId, $returnAsString = false) {
    
    // --- 2. Query Data ---
    $sql = "SELECT M.*, 
                   COALESCE(E1.name_th, U1.username, M.request_by) as requester_name,
                   COALESCE(E2.name_th, U2.username, M.resolved_by) as resolver_name
            FROM " . MAINTENANCE_REQUESTS_TABLE . " M
            LEFT JOIN " . USERS_TABLE . " U1 ON M.request_by = U1.username
            LEFT JOIN " . MANPOWER_EMPLOYEES_TABLE . " E1 ON U1.emp_id = E1.emp_id
            LEFT JOIN " . USERS_TABLE . " U2 ON M.resolved_by = U2.username
            LEFT JOIN " . MANPOWER_EMPLOYEES_TABLE . " E2 ON U2.emp_id = E2.emp_id
            WHERE M.id = ?";
            
    $stmt = $pdo->prepare($sql);
    $stmt->execute([$jobId]);
    $job = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$job) return null;

    // --- 3. Variables ---
    $thaiYear = date('y', strtotime($job['request_date'])) + 43;
    $month = date('m', strtotime($job['request_date']));
    $jobOrderCode = 'MNT-' . $thaiYear . $month . '-' . str_pad($job['id'], 4, '0', STR_PAD_LEFT);
    
    if (!function_exists('formatDateTH_PDF')) {
        function formatDateTH_PDF($date) { return $date ? date('d/m/Y', strtotime($date)) : "-"; }
    }
    if (!function_exists('formatTime_PDF')) {
        function formatTime_PDF($date) { return $date ? date('H:i', strtotime($date)) : "-"; }
    }

    // --- 4. Image Paths ---
    $baseUploadDir = realpath(__DIR__ . '/../../uploads/maintenance/'); 
    $photoBefore = ''; 
    $photoAfter = '';

    if(!empty($job['photo_before_path'])) {
        $fName = basename($job['photo_before_path']);
        $fullPath = $baseUploadDir . DIRECTORY_SEPARATOR . $fName;
        if(file_exists($fullPath)) $photoBefore = $fullPath;
    }
    if(!empty($job['photo_after_path'])) {
        $fName = basename($job['photo_after_path']);
        $fullPath = $baseUploadDir . DIRECTORY_SEPARATOR . $fName;
        if(file_exists($fullPath)) $photoAfter = $fullPath;
    }

    // --- 5. Setup PDF (Compact Mode) ---
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setPrintHeader(false);
    $pdf->SetCreator('MES System');
    $pdf->SetTitle('Job Order ' . $jobOrderCode);
    
    // [FIX] ลด Margin ให้เหลือ 10mm เพื่อขยายพื้นที่เนื้อหา
    $pdf->SetMargins(10, 10, 10); 
    $pdf->SetAutoPageBreak(TRUE, 10);
    $pdf->SetFont('freeserif', '', 10); // ลด Base Font เหลือ 10

    // [FIX] ลดระยะห่างบรรทัด
    $pdf->setCellPaddings(0, 0, 0, 0); 
    $pdf->setCellHeightRatio(1.1); 

    $pdf->AddPage();

    // --- 6. HTML Construction (Compact & Minimal) ---
    
    $html = '
    <style>
        /* [FIX] ปรับขนาดฟอนต์ให้เล็กลงทั้งหมด */
        .header-title { font-size: 16px; font-weight: bold; color: #2c3e50; }
        .header-sub { font-size: 9px; color: #7f8c8d; }
        .job-id { font-size: 12px; font-weight: bold; color: #2c3e50; text-align: right; }
        
        /* ลดขนาดหัวข้อ Section และเส้นกั้น */
        .section-title { font-size: 10px; font-weight: bold; color: #34495e; border-bottom: 1px solid #bdc3c7; line-height: 15px;}
        
        /* ลดขนาด Label และ Value */
        .label { color: #7f8c8d; font-size: 8px; font-weight: bold; text-transform: uppercase; }
        .value { color: #000000; font-size: 9px; }
        
        /* ปรับกล่องข้อความให้กระชับ */
        .box { background-color: #ffffff; border: 1px solid #e0e0e0; padding: 5px; }
    </style>

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="70%">
                <span class="header-title">MAINTENANCE JOB ORDER</span><br>
                <span class="header-sub">ใบแจ้งซ่อมเครื่องจักร (Internal Use Only)</span>
            </td>
            <td width="30%" align="right" style="vertical-align: bottom;">
                <span class="label">JOB NO.</span><br>
                <span class="job-id">' . $jobOrderCode . '</span>
            </td>
        </tr>
    </table>
    
    <div style="height: 10px;"></div>';

    // --- SECTION 1: REQUEST INFO ---
    // [FIX] ลด cellpadding เหลือ 3
    $html .= '
    <div class="section-title">1. REQUEST INFORMATION (ข้อมูลการแจ้งซ่อม)</div>
    <div style="height: 5px;"></div>
    
    <table border="0" cellpadding="3" cellspacing="0" width="100%" style="background-color: #f4f6f7;">
        <tr>
            <td width="30%">
                <span class="label">MACHINE</span><br>
                <span class="value" style="font-weight:bold;">' . htmlspecialchars($job['machine']) . '</span>
            </td>
            <td width="20%">
                <span class="label">LINE</span><br>
                <span class="value">' . htmlspecialchars($job['line']) . '</span>
            </td>
            <td width="30%">
                <span class="label">REQUESTER</span><br>
                <span class="value">' . htmlspecialchars($job['requester_name']) . '</span>
            </td>
            <td width="20%">
                <span class="label">DATE</span><br>
                <span class="value">' . formatDateTH_PDF($job['request_date']) . ' ' . formatTime_PDF($job['request_date']) . '</span>
            </td>
        </tr>
    </table>
    
    <div style="height: 5px;"></div>

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="100%">
                <span class="label">ISSUE DESCRIPTION (อาการเสีย)</span><br>
                <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                    <span class="value">' . nl2br(htmlspecialchars($job['issue_description'])) . '</span>
                </div>
            </td>
        </tr>
    </table>
    
    <div style="height: 10px;"></div>';

    // --- SECTION 2: RESOLUTION INFO ---
    $html .= '
    <div class="section-title">2. RESOLUTION DETAILS (รายละเอียดการซ่อม)</div>
    <div style="height: 5px;"></div>

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="100%">
                <span class="label">TECHNICIAN NOTE (วิธีแก้ไข)</span><br>
                <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">
                    <span class="value">' . nl2br(htmlspecialchars($job['technician_note'] ?? '-')) . '</span>
                </div>
            </td>
        </tr>
    </table>

    <div style="height: 5px;"></div>

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="100%">
                <span class="label">SPARE PARTS (อะไหล่ที่ใช้)</span><br>
                <div style="border-bottom: 1px dotted #ccc; padding: 2px 0;">';
                
    $parts = preg_split('/[\r\n]+/', $job['spare_parts_list'] ?? '');
    $hasParts = false;
    $partsHtml = '';
    foreach ($parts as $part) {
        $part = trim($part);
        if (!empty($part)) {
            $hasParts = true;
            // ใส่ <br> ต่อท้ายเลยเพื่อประหยัดที่
            $partsHtml .= '<span class="value">- ' . htmlspecialchars(ltrim($part, '.-• ')) . '</span><br>';
        }
    }
    $html .= $hasParts ? $partsHtml : '<span class="value">-</span>';
    
    $html .= '  </div>
            </td>
        </tr>
    </table>

    <div style="height: 5px;"></div>

    <table border="0" cellpadding="3" cellspacing="0" width="100%" style="background-color: #f4f6f7;">
        <tr>
            <td width="25%">
                <span class="label">START TIME</span><br>
                <span class="value">' . formatDateTH_PDF($job['started_at']) . ' ' . formatTime_PDF($job['started_at']) . '</span>
            </td>
            <td width="25%">
                <span class="label">FINISH TIME</span><br>
                <span class="value">' . formatDateTH_PDF($job['resolved_at']) . ' ' . formatTime_PDF($job['resolved_at']) . '</span>
            </td>
            <td width="50%">
                <span class="label">TECHNICIAN</span><br>
                <span class="value" style="font-weight:bold;">' . htmlspecialchars($job['resolver_name'] ?? '-') . '</span>
            </td>
        </tr>
    </table>

    <div style="height: 10px;"></div>';

    // --- SECTION 3: IMAGES (Compact) ---
    // [FIX] ลดขนาดรูปเหลือ 110 (จาก 150) เพื่อให้จบในหน้าเดียว
    $html .= '
    <div class="section-title">3. JOB PHOTOS (รูปภาพประกอบ)</div>
    <div style="height: 5px;"></div>

    <table border="0" cellpadding="2" cellspacing="0" width="100%">
        <tr>
            <td width="50%" align="center">
                <div style="border: 1px solid #ccc; padding: 2px; height: 130px;">
                    <div style="font-size: 8px; color: #7f8c8d; margin-bottom: 2px;">BEFORE</div>';
    if ($photoBefore) {
        $html .= '<img src="' . $photoBefore . '" height="110" border="0">';
    } else {
        $html .= '<br><br><span style="color:#ccc; font-size:9px;">- No Image -</span>';
    }
    $html .= '  </div>
            </td>
            <td width="50%" align="center">
                <div style="border: 1px solid #ccc; padding: 2px; height: 130px;">
                    <div style="font-size: 8px; color: #7f8c8d; margin-bottom: 2px;">AFTER</div>';
    if ($photoAfter) {
        $html .= '<img src="' . $photoAfter . '" height="110" border="0">';
    } else {
        $html .= '<br><br><span style="color:#ccc; font-size:9px;">- No Image -</span>';
    }
    $html .= '  </div>
            </td>
        </tr>
    </table>

    <div style="height: 15px;"></div>';

    // --- SECTION 4: SIGNATURES (Compact) ---
    $html .= '
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="5%"></td>
            <td width="40%" align="center" style="border-top: 1px solid #999; padding-top: 3px;">
                <span class="value">' . htmlspecialchars($job['requester_name']) . '</span><br>
                <span class="label">REQUESTER SIGNATURE</span>
            </td>
            <td width="10%"></td>
            <td width="40%" align="center" style="border-top: 1px solid #999; padding-top: 3px;">
                <span class="value">' . htmlspecialchars($job['resolver_name'] ?? '-') . '</span><br>
                <span class="label">TECHNICIAN SIGNATURE</span>
            </td>
            <td width="5%"></td>
        </tr>
    </table>';

    $pdf->writeHTML($html, true, false, true, false, '');

    if ($returnAsString) {
        return $pdf->Output('JobOrder.pdf', 'S'); 
    } else {
        $pdf->Output('JobOrder_' . $jobOrderCode . '.pdf', 'I'); 
    }
}
?>